apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-map
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-files
type: Opaque
data:
  secret.file: |
    bXlwYXNzd29yZA==

  