apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto-message-broker
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        volumeMounts:
          - name: mosquitto-config-volume
            mountPath: /mosquitto/config
            readOnly: true
          - name: mosquitto-secret-volume
            mountPath: /mosquitto/secret
            readOnly: true
            
      volumes:
        - name: mosquitto-config-volume
          configMap:
            name: mosquitto-config-map
        - name: mosquitto-secret-volume
          secret:
            secretName: mosquitto-secret-files
          
